 FROM ubuntu:20.04
 RUN apt-get update && apt-get install --yes --no-install-recommends git make
 LABEL description="Une image contenant git préconfiguré"
 RUN git config --global init.defaultBranch main
